import { defineConfig } from "eslint/config";
import raycastConfig from "@raycast/eslint-config";

// `raycast-env.d.ts` + `dist/` are generated by `ray build`; never lint them
// (matches `ray lint`, and keeps a standalone `eslint .` clean post-build / in CI).
export default defineConfig([{ ignores: ["raycast-env.d.ts", "dist/**"] }, ...raycastConfig]);
